In [1]:
import pandas as pd
import numpy as np
from pykalman import KalmanFilter

In [3]:
New_weather_steps = pd.read_csv("Target_weather_steps.csv")
New_weather_steps = New_weather_steps.drop("Unnamed: 0",axis=1)

In [8]:
# Implements the Kalman filter for single columns.
def apply_kalman_filter(data_table):
    # Initialize the Kalman filter with the trivial transition and observation matrices.
    kf = KalmanFilter(transition_matrices=[[1]], observation_matrices=[[1]])

    numpy_array_state = data_table["value_heart"].values
    numpy_array_state = numpy_array_state.astype(np.float32)
    numpy_matrix_state_with_mask = np.ma.masked_invalid(numpy_array_state)

    # Find the best other parameters based on the data (e.g. Q)
    kf = kf.em(numpy_matrix_state_with_mask, n_iter=5)

    # And apply the filter.
    (new_data, filtered_state_covariances) = kf.filter(numpy_matrix_state_with_mask)

    data_table["value_heart" + '_kalman'] = new_data
    return(data_table)

In [9]:
data_table = New_weather_steps
data_table = apply_kalman_filter(data_table)
display(data_table.iloc[:30])

,start,end,value_steps,value_heart,value_workout,combined,value_heart_kalman
0,2022-01-01 00:00:00,2022-01-01 00:10:00,38.841808,82.000000,no workout,5.0,53.587908
1,2022-01-01 00:10:00,2022-01-01 00:20:00,156.509531,77.500000,no workout,5.0,56.988305
2,2022-01-01 00:20:00,2022-01-01 00:30:00,97.817536,78.500000,no workout,5.0,61.960171
3,2022-01-01 00:30:00,2022-01-01 00:40:00,53.407172,73.500000,no workout,5.0,65.195093
4,2022-01-01 00:40:00,2022-01-01 00:50:00,0.000000,75.500000,no workout,5.0,68.337459
5,2022-01-01 00:50:00,2022-01-01 01:00:00,23.000000,75.455767,no workout,5.0,70.591322
6,2022-01-01 01:00:00,2022-01-01 01:10:00,34.890815,74.500000,no workout,5.0,71.850093
7,2022-01-01 01:10:00,2022-01-01 01:20:00,43.919015,75.000000,no workout,5.0,72.872318
8,2022-01-01 01:20:00,2022-01-01 01:30:00,62.288614,72.000000,no workout,5.0,72.588243
9,2022-01-01 01:30:00,2022-01-01 01:40:00,116.399261,69.666667,no workout,5.0,71.635316
10,2022-01-01 01:40:00,2022-01-01 01:50:00,296.394729,73.000000,no workout,5.0,72.080751
11,2022-01-01 01:50:00,2022-01-01 02:00:00,32.521173,68.500000,no workout,5.0,70.911610
12,2022-01-01 02:00:00,2022-01-01 02:10:00,0.000000,73.000000,no workout,5.0,71.593584
13,2022-01-01 02:10:00,2022-01-01 02:20:00,0.000000,70.333333,no workout,5.0,71.182016
14,2022-01-01 02:20:00,2022-01-01 02:30:00,26.824818,73.000000,no workout,5.0,71.775746
15,2022-01-01 02:30:00,2022-01-01 02:40:00,171.350487,71.000000,no workout,5.0,71.522394
16,2022-01-01 02:40:00,2022-01-01 02:50:00,92.865151,75.000000,no workout,5.0,72.658157
17,2022-01-01 02:50:00,2022-01-01 03:00:00,0.000000,NaN,no workout,5.0,72.658157
18,2022-01-01 03:00:00,2022-01-01 03:10:00,5.000000,NaN,no workout,5.0,72.658157
19,2022-01-01 03:10:00,2022-01-01 03:20:00,0.000000,NaN,no workout,5.0,72.658157
20,2022-01-01 03:20:00,2022-01-01 03:30:00,0.000000,NaN,no workout,5.0,72.658157
21,2022-01-01 03:30:00,2022-01-01 03:40:00,0.000000,NaN,no workout,5.0,72.658157
22,2022-01-01 03:40:00,2022-01-01 03:50:00,0.000000,NaN,no workout,5.0,72.658157
23,2022-01-01 03:50:00,2022-01-01 04:00:00,0.000000,NaN,no workout,5.0,72.658157
24,2022-01-01 04:00:00,2022-01-01 04:10:00,0.000000,NaN,no workout,5.0,72.658157
25,2022-01-01 04:10:00,2022-01-01 04:20:00,0.000000,NaN,no workout,5.0,72.658157
26,2022-01-01 04:20:00,2022-01-01 04:30:00,0.000000,NaN,no workout,5.0,72.658157
27,2022-01-01 04:30:00,2022-01-01 04:40:00,0.000000,NaN,no workout,5.0,72.658157
28,2022-01-01 04:40:00,2022-01-01 04:50:00,0.000000,NaN,no workout,5.0,72.658157
29,2022-01-01 04:50:00,2022-01-01 05:00:00,0.000000,NaN,no workout,5.0,72.658157